### ISSUE TITLE
Two inverter error

### ISSUE THREAD

**Issue by matteocaretta72** [Pho3niX90/solis_modbus#95]
When I configure two inverters on two different IP addresses in the integration one stops working, and the commands control the other inverter
two Inverter S5-EH1P 6kw

**Comment by Pho3niX90** [comment]
Is this for all commands, or specific ones? How are you triggering the commands? Via the provided buttons?

**Comment by Pho3niX90** [comment]
@matteocaretta72 can you try https://github.com/Pho3niX90/solis_modbus/releases/tag/1.5.5

**Comment by Pho3niX90** [comment]
Should be fixed in `1.5.6`

**Comment by matteocaretta72** [comment]
Updated but it doesn't work.
When I add the first inverter it works well, by adding the second the first one no longer works, while the second one has data that always changes in a confusing way.
The second inverter is a zeroCO2 but still the same model.
Do you have any suggestions please

**Comment by Pho3niX90** [comment]
> Updated but it doesn't work. When I add the first inverter it works well, by adding the second the first one no longer works, while the second one has data that always changes in a confusing way. The second inverter is a zeroCO2 but still the same model. Do you have any suggestions please

Could you perhaps provide some logs. 
Does each inverter at least have it's own sensors/entities?
